# Generated by Django 5.2.4 on 2025-08-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('langauge', models.CharField(default='None', max_length=50)),
                ('genre', models.CharField(default='None', max_length=200)),
                ('duration', models.CharField(default='None', max_length=50)),
                ('cast', models.TextField(default='None')),
                ('director', models.CharField(default='None', max_length=100)),
                ('release_date', models.DateField(blank=True, default='2025-01-01', null=True)),
                ('image', models.ImageField(upload_to='movie_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
