# Generated by Django 5.2.4 on 2025-08-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_theatre_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentshow', to='api.movie'),
        ),
    ]
