# Generated by Django 5.2.4 on 2025-08-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_show_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre', to='api.theatre'),
        ),
    ]
