# Generated by Django 5.2.4 on 2025-08-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
